### ISSUE TITLE
Add Igalia Coding Experience Internship

### ISSUE THREAD

**Issue by palash25** [tapasweni-pathak/SOC-Programs#82]
- Remote
- Open Source
- Paid

https://www.igalia.com/about-us/coding-experience

**Comment by Naveenaidu** [comment]
Sure! Would love to do that. I'll create a PR for it soon.

**Comment by Naveenaidu** [comment]
@palash25  Please have a look at the PR.

**Comment by palash25** [comment]
Looks fine but you need to make a PR to this repo not your fork :stuck_out_tongue:

**Comment by Hyperion101010** [comment]
Perhaps you forgot to add the deadline on the website, I filed a query to the contact page a couple of weeks ago regarding the timeline for Igalia Coding experience program but wasn't answered back. Can you please let me know about the time details of the program,  update it on the website itself so that everyone can plan their workflow accordingly.

**Comment by Naveenaidu** [comment]
Hey @Hyperion101010 AFAIK there's no deadline for Igalia Coding Experience. And we aren't actually related to Igalia in any way. So unfortunately we do not have the details regarding the details of the Program, nor do we have the access to update any information on the Igalia website.

From my personal experience, When I applied last year - They didn't reply to my mail too. Try contacting the people of Igalia via LinkedIN. I guess that might help :)

**Comment by TG1999** [comment]
@Naveenaidu did you applied last year, if yes did you get selected. And what did you gave in the other documents field.
Thanks
